### ISSUE TITLE
Unclear difference between `icon-set` and `ui-icons`

### ISSUE THREAD

**Issue by havgry** [youseedk/dna#140]
I'm not sure what the difference is between the icon types other than the canvas size, and it's not clear from the documentation when to use what.

**Examples versions of left arrow icon:**
https://github.com/youseedk/dna/blob/master/src/assets/svg/ui-icons/arrow-left.svg
https://github.com/youseedk/dna/blob/master/src/assets/svg/icon-set/back-left.svg
https://github.com/youseedk/dna/blob/master/src/assets/svg/icon-set/arrow-left.svg

My initial thought was that UI icons are for embedding in components/elements/thingies but that doesn't seem to be the case (e.g. input example), and some of them even share the same names (which complicates things in `dna-react`). Help me and other users make sense of this :)

**Comment by grandorf** [comment]
Thanks for input. We will look into this.

**Comment by havgry** [comment]
I'm closing this as I don't see any progress anytime soon :) I've gone ahead and implemented the two types of icons in dna-react. It could be more clear to the designer or developer when to use which icons but for now it works well enough.

**Comment by grandorf** [comment]
I still think we should look into this. I will re-open the issue.

**Comment by havgry** [comment]
@grandorf Is this something we should talk to Daniel about? I think this is mainly about making the documentation clearer.

**Comment by havgry** [comment]
Daniel suggested to merge `icon-set` and `ui-icons` which I think is a great idea. That means we'll have a single set of icons moving forward and each icon should work everywhere (shortcut, input, button, notification and so on). This simplifies everything a great deal.

Due to renaming of certain icons this will be a breaking change (albeit a minor one). We might need to do some tweaking of some elements in terms of visual alignment due to the "lighter" appearance of the new icons.

Furthermore, we agreed to include PNG versions of the icons in the documentation.

**Comment by grandorf** [comment]
still waiting for icons...
