### ISSUE TITLE
Left-aligned icon in button

### ISSUE THREAD

**Issue by havgry** [youseedk/dna#155]
In a majority of all cases I think it makes sense to right-align the icon like so:

![expand](https://user-images.githubusercontent.com/3898396/55884730-d81e2b80-5ba8-11e9-8b63-47146b1ead38.PNG)

But Venelin pointed out that they use the button as a "back" button for navigational purposes which just might be the exception to that rule:

![image](https://user-images.githubusercontent.com/3898396/55883865-5aa5eb80-5ba7-11e9-8339-1dfcef9c36db.png)

In terms of styling it's a trivial change but I'm curious to know if there is any UX or design concerns behind the current way it is?

**Comment by grandorf** [comment]
It makes sense to show the arrow on the left side in a back-button like this. We should allow this.
We will try to add it as an option in an upcoming release.
