### ISSUE TITLE
Fractal theme styles being applied to components

### ISSUE THREAD

**Issue by havgry** [youseedk/dna#159]
Browsing through the documentation I see a lot of inconsistencies between the expected behaviour and the actual behaviour:
<img width="467" alt="Screenshot 2019-04-14 at 17 21 08" src="https://user-images.githubusercontent.com/3898396/56095210-ab388400-5eda-11e9-87eb-c6e14d19bd55.png">

They are caused by the Fractal theme being used. When using the full screen preview it's working as expected:

<img width="303" alt="Screenshot 2019-04-14 at 17 29 01" src="https://user-images.githubusercontent.com/3898396/56095257-0ec2b180-5edb-11e9-8e2e-8503071b307a.png">

Coincidentally, it's also a pretty good argument against attempting to safeguard for overrides like these :)

**Comment by kimblim** [comment]
I've created a PR for this: #162 

I actually think this is a good argument for safeguarding against issues like this, I just think it proves that it's hard and not something that we can ever do 100%. 

In my opinion, you guys (@grandorf, @havgry, @vercell) need to have a discussion on removing the specificity hack in v2.x.x and then setting a requirement that globally set styles on elements is not permitted for anyone who wishes to use DNA. I think that limits the usage and makes it less applicable (but more bulletproof).

**Comment by grandorf** [comment]
I don't see a reason to remove the specificity hack. But we should consider to add to the documentation site that global styling on elements (and locally because we use BEM) should be avoided of all costs

**Comment by grandorf** [comment]
@havgry because Kim is not on the project anymore. Would you like to help fixing this bug? There is a PR for it but as you mention yourself there is more components would this issue. This is because they are embedded on site as you already know.

**Comment by grandorf** [comment]
Otherwise I will look at it when I'm back from vacation the 7th of May ;-)

**Comment by havgry** [comment]
This can be closed when https://github.com/youseedk/dna/pull/165 has been merged.
