### ISSUE TITLE
Lobotomized owl selector broken after specificity increase hack

### ISSUE THREAD

**Issue by havgry** [youseedk/dna#160]
The hack introduced in ef225544d35499c3c496c9d4c6c09538645d96fc to boost the specificity of all selectors appears to have broken the lobotomized "owl" selectors in the notification, tooltip, and typography components. Example: https://github.com/youseedk/dna/blob/master/src/assets/scss/elements/ys-typography.scss#L39

So now it's being compiled into:
```
html:not(#ys-specificity) .ys-list__item + html:not(#ys-specificity) .ys-list__item
```
instead of:
```
.ys-list__item + .ys-list__item
```

There are a lot of ways to fix this but I honestly think we should reconsider the addition of `html:not(#ys-specificity)` to all selectors. It seems to do more harm than good.

**Comment by kimblim** [comment]
I've created a PR for this.

I agree that the error occured due to the specificity fix, but I don't think the fix is to blame — I am ;)

**Comment by grandorf** [comment]
merged
