### ISSUE TITLE
Move specificity hack to a CSS post-processor

### ISSUE THREAD

**Issue by havgry** [youseedk/dna#174]
I just stumpled upon these broken selectors:

https://github.com/youseedk/dna/blob/ff19418489dff04983623467afafd9cb860c7e31/src/assets/scss/elements/ys-input-field.scss#L92
https://github.com/youseedk/dna/blob/ff19418489dff04983623467afafd9cb860c7e31/src/assets/scss/elements/ys-input-field.scss#L116
https://github.com/youseedk/dna/blob/ff19418489dff04983623467afafd9cb860c7e31/src/assets/scss/elements/ys-select.scss#L97
https://github.com/youseedk/dna/blob/ff19418489dff04983623467afafd9cb860c7e31/src/assets/scss/elements/ys-textarea.scss#L58

It has been bothering me for a while that we're not able to use common SCSS syntax after the introduction of the specificity hack which is clearly error-prone. I suggest we revert the changes in https://github.com/youseedk/dna/pull/161 and use a postprocessor like [postcss-prefix-selector](https://github.com/RadValentin/postcss-prefix-selector#usage-with-postcss) and simply prefix all selectors with `html:not(#ys-specificity)`. I'm not exactly a gulp expert but it should be pretty straight-forward to fix.

Any thoughts?

**Comment by grandorf** [comment]
Great idea. Should be fairly easy to do. I will look into this.

**Comment by grandorf** [comment]
I have created a PR with a fix. I did file comparison on most of the output files and they all passed.
