### ISSUE TITLE
Suggestion to add anchor element to rich text component

### ISSUE THREAD

**Issue by havgry** [youseedk/dna#179]
The rich text component adds styling to heading elements, lists, and paragraphs but not to anchor elements. Is this by design? It seems like something that would make sense to add but it's not something I necessarily need right now.

**Comment by grandorf** [comment]
@dsdo so you have an opinion about this?

**Comment by dsdo** [comment]
@grandorf is gonna look at it 👍

**Comment by grandorf** [comment]
@dsdo how is this going?

**Comment by grandorf** [comment]
We have decided, for now, that anchor links should just appear the same as normal text-links.
