### ISSUE TITLE
Remove FOCUS STATE (border) from some elements

### ISSUE THREAD

**Issue by dsdo** [youseedk/dna#182]
We have identified that the **browser default focus state** it has been shown on several elements even when you are not navigating with your keyboard. We should fix that.

We should remove the FOCUS STATE BORDER on all the components listed below:

- Input Fields
- Radio Buttons
- Checkbox
- Slider
- Select
- Textarea

Thank you,

<img width="993" alt="Screenshot 2019-05-23 at 09 57 02" src="https://user-images.githubusercontent.com/50944754/58235680-981e9c80-7d41-11e9-99dd-f48019e50472.png">
<img width="986" alt="Screenshot 2019-05-23 at 09 57 16" src="https://user-images.githubusercontent.com/50944754/58235682-981e9c80-7d41-11e9-9b94-b2287cb93a00.png">
<img width="982" alt="Screenshot 2019-05-23 at 09 57 38" src="https://user-images.githubusercontent.com/50944754/58235683-98b73300-7d41-11e9-9e6c-fb539ac05770.png">

**Comment by havgry** [comment]
Hi Daniel!

Just to provide some context: It's not possible to distinguish between focus by tabbing and focus by clicking. Unstyled elements like a vanilla radio button will not get a blue outline on click, but the moment we start styling it, it will receive the blue outline on click as well.

That being said, we can remove the blue outline for specific elements but it's important that we replace it with something else. I just checked with the design system and it seems that we're currently missing focus states for the radio and checkbox elements, which is something we should fix, but as far as I can see there's no defined focus state for the slider element. That's something you should look into.

Also, I think it would be nice to have different states for hover and focus. If we remove the blue outline there will be very little visual difference between hovering an input field and then clicking the input field - only the cursor will change. Anyway, that's just my opinion.

**Comment by grandorf** [comment]
This sounds like a job for the new CSS feature :focus-visible
https://css-tricks.com/keyboard-only-focus-styles/

**Comment by dsdo** [comment]
I'll cal a quick meeting in half an hour so we can talk :D
