### ISSUE TITLE
Add 'Is required' feature to the input

### ISSUE THREAD

**Issue by razvandk** [youseedk/dna#195]
At the moment we are missing the visuals for when an input field is mandatory/required

**Comment by dsdo** [comment]
**I'll look into it**

**Comment by grandorf** [comment]
It is a UX decision that we don't show fields that are mandatory/required. This is because all fields are mandatory except optional fields that should include the word `(optional)` in the label text.
Does that makes sense?

**Comment by grandorf** [comment]
I'll add this example in the documentation site.
