### ISSUE TITLE
New Password Input Fields

### ISSUE THREAD

**Issue by dsdo** [youseedk/dna#202]
Hey @grandorf 

Here is the link to the invision prototype:

**_Username:
https://yousee.invisionapp.com/share/R4TCONJ87TB#/377886028_iPhone_XS_756_X_812_Px_4_**

**Password:
https://yousee.invisionapp.com/share/6CTCOW3MQYN#/377886132_iPhone_XS_756_X_812_Px_D**

And I'm also adding the files attached.
![passwords](https://user-images.githubusercontent.com/50944754/62630186-beaaa780-b92e-11e9-9b79-1a7e25cd626c.png)

**Comment by grandorf** [comment]
Waiting for design and ux decides how all input fields shoule look and behave.

**Comment by grandorf** [comment]
This task is depending on a bigger redesign of all input fields. I will close the issue because it will be fixed when the input fields v2 is ready to be implemented.
