### ISSUE TITLE
Button scaling issue

### ISSUE THREAD

**Issue by Nomi97** [youseedk/dna#210]
Button is overflowing the container
![image (2)](https://user-images.githubusercontent.com/21775402/65947859-662ced80-e439-11e9-8031-0a8eb382946e.png)

**Comment by havgry** [comment]
What's the expected result?

**Comment by grandorf** [comment]
I am not sure. Maybe we should consider to bring it up as a small topic for next guild

**Comment by havgry** [comment]
I think it's a design issue, honestly :)

**Comment by grandorf** [comment]
Nobody else has rasied this issue and it's 4 months old. I will close the task with no fix as it does not seem important.
