### ISSUE TITLE
etica font bold should be "700" and not "800"

### ISSUE THREAD

**Issue by grandorf** [youseedk/dna#211]
According to the documentation on https://fonts.adobe.com/fonts/lft-etica#details-section bold text should he `font-weight: 700` and not 800 as in DNA.
We should fix this.

**Comment by havgry** [comment]
Where is this applicable, specifically?

https://github.com/youseedk/dna/search?q=800

**Comment by grandorf** [comment]
All the places in your search query it should be changed.

**Comment by havgry** [comment]
But to me it seems like it's only the documentation that's wrong.

**Comment by grandorf** [comment]
Yes it's only documentation but we still need to fix it. I have bow changed the label to be `documentation` if this is what your motive was?
