### ISSUE TITLE
Input selection bug

### ISSUE THREAD

**Issue by razvandk** [youseedk/dna#217]
I have an input field with an address when i want to change the number and i want to select a specific location in the input, but it sets the cursor in a different location.
This bug is caused by having different font-weight for when input is active vs when its not active.

![](https://media.giphy.com/media/XfPCZ6wHBqCnKULzxd/giphy.gif)

**Comment by grandorf** [comment]
Good catch. I will find a solution to this.

**Comment by grandorf** [comment]
The best solution was to simple remove the bold text when hovering.
Also, this will make the hover-effect on the input-fields more clear. Not it's not just the shadow but also the text changing when hovering.
