### ISSUE TITLE
Upload 2 NEW ICONS

### ISSUE THREAD

**Issue by dsdo** [youseedk/dna#224]
Hey,

We have 2 news icons that have to be uploaded to DNA.

Payment Return **(please keep the name so its the same on the Design System File)**
Globe **(please keep the name so its the same on the Design System File)**

Tks 

[New Icons.zip](https://github.com/youseedk/dna/files/3885794/New.Icons.zip)

**Comment by havgry** [comment]
Everything needed for the icons are autogenerated, so maybe we should spend 5 minutes outlining how to add, update, and remove icons directly from GitHub? That way you (or any other designer) could create a pull request quite easily :)

**Comment by havgry** [comment]
We agreed to meet this week and go over how to make a PR. I'm closing the two issues.

**Comment by grandorf** [comment]
@havgry remember to clean up and optimize the SVG code if necessary. Sometimes the output is very messy and not high quality.

**Comment by grandorf** [comment]
I am actually not entirely sure this is a good idea. Because Daniel and designers don't pay attention to this.
The SVG files should be high quality because they will also get used in TvLab where they convert them to xml-vector for Android and also if we need to animate them later on.

**Comment by havgry** [comment]
_Everything_ that goes into DNA should be high quality! And it will go through review like any other piece of code. I don't see the problem 🙂

**Comment by grandorf** [comment]
Ok
