### ISSUE TITLE
Utilise npmignore to circumvent docs publish issue

### ISSUE THREAD

**Issue by Dechowmedia** [youseedk/dna#226]
One way to mitigate the issue going forward is to introduce a `.npmignore` file
It retains the format of a normal ignore file - only you choose to tell it which files are not for "redistribution" when you publish.

This could theoretically mitigate the issue - if a manual push is ever needed or warranted

https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

One could then keep the docs like so 
```
src/docs
src/elements
```
(omitting tokens as they may have a better use case) 

Have not assigned any as I just want it to be highlighted as a way of action - but would you guys want this I can easily add it

**Comment by grandorf** [comment]
I don't think we need this because everything is automated through the build pipeline. But thanks for the suggestion. Will close this issue for now.
