### ISSUE TITLE
Investigate options for focus state workaround

### ISSUE THREAD

**Issue by havgry** [youseedk/dna#228]
We briefly discussed the option to disable `outline` unless the user interacts by keypress. This is something that's worth looking into, even though it feels a bit... iffy :) The idea is to add a modifier class to body if the user interacts with the keyboard and then removing it again once the user clicks/touches/whatever. This gives us the option to have a customized focus state only visible when the user navigates with the keyboard.

@grandorf will try to see if he can find implementation examples from other websites.

**Comment by havgry** [comment]
Input fields are a known exception to this rule.

**Comment by grandorf** [comment]
I will close this issue. We can always re-open or create a new issue later when/if needed
