### ISSUE TITLE
Proposal to remove `alternative` variant on selects

### ISSUE THREAD

**Issue by havgry** [youseedk/dna#230]
With the new look being introduced in https://github.com/youseedk/dna/pull/229, the `alternative` select looks awfully similar to the default one (alternative at the bottom):

![alternative](https://user-images.githubusercontent.com/3898396/71575511-824e3280-2aed-11ea-8f38-f27b1d09753e.PNG)

... Only it doesn't really have focus/hover states. It seems like it's only the combination of alternative and light, that's any different:

![alternative2](https://user-images.githubusercontent.com/3898396/71575692-35b72700-2aee-11ea-9c26-7c9dd7064d0e.PNG)

Are there any use cases for this variant or can we simplify the code?

**Comment by grandorf** [comment]
The last recap from the DNA Guild:

**Form inputs**
No one on Yousee.dk is using the dark version of inputs, selects, and textareas and they will be removed according to the 80/20 rule. Magnus will take care of this.

I guess it makes sense for you to clean all this up in same task.

**Comment by grandorf** [comment]
Music Lab seems to use the dark versions. We need to take this up at a guild for at strategy.

**Comment by grandorf** [comment]
Should we close this?

**Comment by havgry** [comment]
Someone else should make the call :) I still think it's valid although not super important.

**Comment by grandorf** [comment]
I make the call to close this. It's almost a year since you created the task and we haven't fixed the issue. It is probably not something we should prioritise then.
