### ISSUE TITLE
Dropshadow in tabs looks weird with rounded corners

### ISSUE THREAD

**Issue by Nickhoyer** [youseedk/dna#231]
![image](https://user-images.githubusercontent.com/9862931/72152092-45feba00-33aa-11ea-94dd-60cd867f8c23.png)
Unselected (looks good)

![image](https://user-images.githubusercontent.com/9862931/72152105-51ea7c00-33aa-11ea-8bfb-e375bbbf7602.png)
Selected (look at corners on the right)

**Comment by havgry** [comment]
This is definitely a bug: https://dna.yousee.dk/docs/components/interactions/tabs.html (change the background color of `.element-preview__inner` to see it clearly).

You're welcome to submit a PR ;)

**Comment by grandorf** [comment]
@Nickhoyer you have been assigned to this task for almost a year. I think it's fair to say that this is not important and not something that we should prioritise. I will close the issue.
