### ISSUE TITLE
ADD new icons

### ISSUE THREAD

**Issue by dsdo** [youseedk/dna#239]
Hey guys,

They're a bunch of new icons we need to include at DNA.
I hear that Devs at Tv lab are only accepting using icons that are at DNA so let's help them. 😊

Thank you,
Daniel

[New Icons.zip](https://github.com/youseedk/dna/files/4235660/New.Icons.zip)

**Comment by grandorf** [comment]
Below icons do not follow our guidelines. Please remove the `transform` attribute in the code from them.

- 5G
- Unplayable
- Repeat one
- External Link
- eSIM
- Compare

Also, please confirm that the names are 100% correct. After releasing them we can NOT change the name again without creating a major breaking change in DNA, which should be avoided.

**Comment by dsdo** [comment]
Hi Michael, all of them are fixed now. ;)

[icons.zip](https://github.com/youseedk/dna/files/4297599/icons.zip)
