### ISSUE TITLE
RENAME 1 Icon

### ISSUE THREAD

**Issue by dsdo** [youseedk/dna#240]
This is basically **renaming an icon** attached so we are consistent on the naming across different platforms. ;)

[Rename.zip](https://github.com/youseedk/dna/files/4235670/Rename.zip)

**Comment by grandorf** [comment]
@dsdo please ret rid of `transform="translate(12.492 11.869)"`in the SVG file and upload a new version 🙂

**Comment by dsdo** [comment]
Fixed! ;)

[Player Orientation Lock.svg.zip](https://github.com/youseedk/dna/files/4297622/Player.Orientation.Lock.svg.zip)
