### ISSUE TITLE
Add type on build

### ISSUE THREAD

**Issue by razvandk** [youseedk/dna#242]
Implement functionality that adds types for our scss/css in order to use them as css modules.

This functionality will enable intellisense in the editor.

E.g.
``` typescript
import {
  ysNotification,
  ysNotificationWarning,
  ysNotificationSuccess,
  ysNotificationError,
} from '@youseedk/dna/css/elements/ys-notification.css';

// ...

<div
      className={cx(ysNotification, {
        [ysNotificationWarning]: type === 'warning',
        [ysNotificationSuccess]: type === 'success',
        [ysNotificationError]: type === 'error',
      })}>
</div>
```

**Comment by razvandk** [comment]
This is on hold until we find out exactly which format we need to create the variables

**Comment by grandorf** [comment]
Is this still on hold? Can we close the issue and then you can create a new issue when there is actually a need? The task is over 6 months old now.
