### ISSUE TITLE
Addition request to typography in the DNA

### ISSUE THREAD

**Issue by OVA-robin** [youseedk/dna#249]
We need to add Bold to body text. 
- On mobile: Add bold 16.
- On desktop: Add bold 20.

**Comment by OVA-robin** [comment]
I added with red where i'm using 20 bold on desktop: https://www.figma.com/file/pEHywaitVCFFj7mBOOQ18J/Servicetjek-1?node-id=0%3A14198

Here are some 16 bold examples on Mobile:
https://www.figma.com/file/38ArGNyG7kdQDU1qx1tQ45/Manuel-Steps?node-id=904%3A20091

**Comment by grandorf** [comment]
This should be handled locally in Digital Help. It will not be part of DNA. Closing the issue again :)
