### ISSUE TITLE
TECHNOLOGY.md

### ISSUE THREAD

**Issue by grandorf** [youseedk/dna#250]
We want an overview of the technology landscape in Nuuday. The technologies in use inapplications and services as well as the technologies we have actively abandoned.The overview creates a baseline for technology selection; we promote the adaption oftechnologies actively in use and recommended by the developers.We want to do this overview in a structured manner so we can collect and combine thetechnology selection across Nuuday.In the root of every application repository, we create a TECHNOLOGY.md file.

**Comment by Dechowmedia** [comment]
Question why is DNA hosting this?
Shouldn't this be more of a thing for the Source Code Consolidation project?

In that way we keep source code and technologies used across nuuday in tact with the tech actually used going on forward :) - just a thought

**Comment by jorckworm** [comment]
Where is the documentation for the TECHNOLOGY.md file? 
I haven't heard about it before now.
