### ISSUE TITLE
6 new icons for DNA

### ISSUE THREAD

**Issue by OVA-robin** [youseedk/dna#255]
[6 new icons.zip](https://github.com/youseedk/dna/files/4890558/6.new.icons.zip)

**Comment by havgry** [comment]
What's the process for adding icons? Do they need approval? I don't mind making the PR.

**Comment by OVA-robin** [comment]
The process is that I post them here so someone can add them to the DNA som my frontender can use them.

**Comment by havgry** [comment]
1. The Error404 already exists, as far as I can see - it's just named `unplayable`. I suggest we keep the existing icon and name.
2. The `landline` name is already taken for a different icon. Again, I'm not sure what the process is for adding icons.

**Comment by OVA-robin** [comment]
The "Error404" doesn't exists. The one called "unplayable" is a tv with an X. "Error404" is a laptop with an X.

ok, since "Landline" already exists I will rename the icon to DSL, but then I also have to rename cable to COAX so they follow the same naming.

**Comment by OVA-robin** [comment]
Skal jeg oploade ikonerne igen med de nye navne eller gør du det selv?

**Comment by havgry** [comment]
@OVA-robin I'll finish up the pull request today. I don't need anything further from you :) Hopefully, we can get this out soon.
