### ISSUE TITLE
Accessibility role for Spinner component

### ISSUE THREAD

**Issue by MBehtemam** [youseedk/dna#259]
it's a good idea to add and suggest accessibility roles for components. there are a lot of benefit for having role also it help me for writing tests in React  because `react-testing-library` encourage us to select and find element on DOM by their roles, so I don't need to pass `test-id`.

**Comment by grandorf** [comment]
@MBehtemam can you help to fix this?

**Comment by grandorf** [comment]
@MBehtemam please add some sources or information about this. And maybe suggest a solution to this issue?
