### ISSUE TITLE
Add helper-classes/utilities-for-text

### ISSUE THREAD

**Issue by Nomi97** [youseedk/dna#260]
I want utilities classes added for text like `text-center`, `text-bold` or `text-semi-bold`

**Comment by grandorf** [comment]
I am sure we want this. There are soo many helper classes in Bootstrap. YouSee DNA is **not** Bootstrap. We are only using the grid. If you want to utilise Bootstrap more comprehensively I think you need to add Boootstrap as a dependency in your site as you have now.
But let us hear what others think. If many others share your wish then of cause we should consider it!

**Comment by grandorf** [comment]
By the way. We do have this in DNA: https://dna.yousee.dk/docs/components/helper-classes/utilities-for-layout

If we have a handful of helper classes we keep using all the time then we can add those!

**Comment by Nomi97** [comment]
From what i can see Bootstrap has Components, Layout and Utilities and DNA covers 2 of these. It would be nice if we could make bootstrap obsolete and only rely on DNA for all our styles.

**Comment by Nomi97** [comment]
And DNA is all ready using some of the bootstrap utilities like  https://dna.yousee.dk/docs/components/helper-classes/media-queries.html so it would be nice if we could add a few more

**Comment by Nomi97** [comment]
I figured adding all the utilities in one PR might be to much so changing this issue to utilities-for-text specifically
