### ISSUE TITLE
Large version of progress bar

### ISSUE THREAD

**Issue by razvandk** [youseedk/dna#262]
I would like to have a thicker version of the progress bar. At the moment we have the `height: .25rem` which doesn't work well for what we are asked to build. This is mostly a question if i should implement this in our application only or should i just add the functionality here?

Current functionality:
https://dna.yousee.dk/docs/components/feedback/progress-bar.html

Extra property:
![Screenshot 2020-09-16 at 11 21 18](https://user-images.githubusercontent.com/3015240/93327452-a936cb00-f81a-11ea-9d35-472589d21672.png)

**Comment by havgry** [comment]
My personal opinion is that these two variants are so similar we should attempt to modify the existing one. Is anyone familiar with the existing progress being used anywhere?

**Comment by grandorf** [comment]
Seems fixed.
