### ISSUE TITLE
3 new icons for DNA

### ISSUE THREAD

**Issue by OVA-robin** [youseedk/dna#267]
1.
There is an error in an icon in the DNA.
The icon: "external link" must be replaced with the attachment icon with the same name.

2.
The "Article" and "Series Record" icons should be added to the DNA.

[3 icons.zip](https://github.com/youseedk/dna/files/5401773/3.icons.zip)

**Comment by havgry** [comment]
What about the existing series-record icon?

<img width="60" alt="Screenshot 2020-10-19 at 16 53 26" src="https://user-images.githubusercontent.com/3898396/96467826-a2411500-122b-11eb-883b-c91624a8cf71.png">

**Comment by OVA-robin** [comment]
Ups. The icon i uploaded should be called: player-series-record. And should not overwrite any icon

**Comment by OVA-robin** [comment]
Any news on this one?

**Comment by MichellDranig** [comment]
I'm looking into it now
