### ISSUE TITLE
Change the green link color on YouSee.dk

### ISSUE THREAD

**Issue by OVA-robin** [youseedk/dna#269]
Our current link color does not meet the availability requirements we follow when font size comes down to size 16 on mobiles. The contrast must be increased. Therefore, we change all links on the entire YouSee to a darker color so that we can still comply with the availability requirements.

The green link color # 1FAB2E should be changed to: # 1A8924.

The new darker green is called: Digital Dark Grass

**Comment by grandorf** [comment]
Maybe we now need to tweak it a little when it's used on dark backgrounds?

**Comment by OVA-robin** [comment]
No. We already have the rule that links on dark and colored bacgrounds are underlined and have the same color as the text.
