### ISSUE TITLE
3 new icons for DNA (4G - Mobile-Wifi - Attach-file)

### ISSUE THREAD

**Issue by OVA-robin** [youseedk/dna#271]
[3 icons.zip](https://github.com/youseedk/dna/files/5494363/3.icons.zip)

Please add these 3 icons to the DNA icon library.

**Comment by MichellDranig** [comment]
I'll fix it

**Comment by OVA-robin** [comment]
Why can't I see the 3 new icons in the icon library on DNA? https://dna.yousee.dk/docs/design-guidelines/icons.html

**Comment by grandorf** [comment]
We have not made a new release yet. I want us fix a few more tasks before we release.

**Comment by grandorf** [comment]
It's normal to include more tasks when we release to a minor version. It was a mistake that @Lubbe91 closed the issue. I have reopened it again.

**Comment by OVA-robin** [comment]
what about issues 267 That is also 3 icons

**Comment by grandorf** [comment]
That is why we have not released yet. When that task and a few other issue are fixed we will release.

**Comment by razvandk** [comment]
@OVA-robin why is the 4G icons `41x40` no `40x40` like all the others? i assume it is a mistake, what can we do to fix it?

**Comment by OVA-robin** [comment]
[4G.svg.zip](https://github.com/youseedk/dna/files/5523835/4G.svg.zip)
That sound strange. Here it is 40x40. Try this one
