### ISSUE TITLE
Validation for input fields should not be green on hover

### ISSUE THREAD

**Issue by grandorf** [youseedk/dna#280]
If you hover an input field that has an error and is invalid you get the green color. This could be confusing for customers and we should consider it as a bug. The red color needs to stay red until the value is validated.

Steps to reproduce the issue:
Go to https://dna.yousee.dk/docs/components/form-elements/input-field and try to hover input field with invalid input

Here I am hovering an invalid field.
![image](https://user-images.githubusercontent.com/21218852/98873086-01372a00-2478-11eb-84f1-0a719678d78c.png)

**Comment by Dechowmedia** [comment]
It is a mystery to me why GitHub sometimes forgets to do these things...

**Comment by grandorf** [comment]
It's because it's not released yet.

**Comment by grandorf** [comment]
Please don't close issues that are not fixed yet. It will happen automatically when master is pushed :)

**Comment by Dechowmedia** [comment]
:+1: sorry - saw it and thought it was a bug <3
