### ISSUE TITLE
Notifications/Feedback Messages

### ISSUE THREAD

**Issue by OVA-robin** [youseedk/dna#288]
We should only have 1 type of small notifications and 1 type of large of notification. 
I have seen different squads make all sorts of variations so let't put this in DNA.
On a UI meeting we agreed on this design for the big Notifications/Feedback Messages

https://www.figma.com/file/21BhM7ixlKsfwr2RUUHKdL/Design-System-Final?node-id=2%3A2

**Comment by havgry** [comment]
Sounds like a good idea. Do you mind sharing the screenshots instead of a link to Figma? Not everyone has access to Figma :)

**Comment by OVA-robin** [comment]
![Skærmbillede 2021-01-18 kl  18 15 06](https://user-images.githubusercontent.com/65396024/104945526-2c2e8480-59b9-11eb-81d4-818ffb883402.png)
![Skærmbillede 2021-01-18 kl  18 20 35](https://user-images.githubusercontent.com/65396024/104946186-ef16c200-59b9-11eb-851b-b9e396b9094b.png)

**Comment by laukondrup** [comment]
Closing after talking with @OVA-robin 

The requirements changed since the creation of this task so a new and updated task will be created.
