### ISSUE TITLE
2 new icons to be added to the DNA library

### ISSUE THREAD

**Issue by OVA-robin** [youseedk/dna#291]
[2 new icons for yousee.zip](https://github.com/youseedk/dna/files/6375289/2.new.icons.for.yousee.zip)
Booster.svg
Voicemail.svg
Please add these icons to the DNA

**Comment by laukondrup** [comment]
Hi @OVA-robin, I've made the changes in both DNA and DNA React but I'm waiting on @grandorf to help me with the release so you can use it.

I'd expect it to be out tomorrow but I'll keep you updated when it's released.
