### ISSUE TITLE
new icon for DNA

### ISSUE THREAD

**Issue by OVA-robin** [youseedk/dna#293]
Ring til udland abonnement
[dk-til-udland.svg.zip](https://github.com/youseedk/dna/files/6435096/dk-til-udland.svg.zip)

Call the icon: `call-abroad`

**Comment by laukondrup** [comment]
The icon will probably be ready tomorrow. I'll keep you updated 👍

**Comment by laukondrup** [comment]
It's deployed now in version:
DNA: 2.9.0
DNA-React: 1.1.1-next.4
