### ISSUE TITLE
Create separate, importable stylesheet containinng font-face rules

### ISSUE THREAD

**Issue by havgry** [youseedk/dna#83]
I'm importing the compiled and minified CSS on a component basis like so:

```
import '@youseedk/dna/css/elements/ys-button.css'
```

But since the font-face rules are only a part of the bundle, I can't really import them without importing the whole bundle. For now, I've copy-pasted the rules into the repo but I'd prefer to import them directly and also not have to deal with optimizing CSS at all.

I'm proposing that a separate stylesheet is created containing only the webfonts. I don't mind making a PR but I'm curious to know if there's a reason for the way it is now :)

**Comment by kimblim** [comment]
@havgry 
The thinking behind only having it in the bundle and adding the font-files in the package as well was that developers who use the components individually would most likely also include the fonts in "their own way".

However, it makes sense to make it as easy and accessible as possible, so we'll add a css-file with only the webfont imports.

**Comment by kimblim** [comment]
https://github.com/youseedk/dna/pull/86

**Comment by havgry** [comment]
Yep, I like the fact that it's not required. But I also like that there's one default way of importing the fonts. Anyway, thanks :) I'll use that one as soon as you publish a new package.

Perhaps, down the road, it would make sense to create a separate package for all the basic stuff that's _not necessarily_ required but more like a nice to have, and include that as a peer dependency in dna and dna-react.
